// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCurriculum.Entities;

#nullable disable

namespace MyCurriculum.Migrations
{
    [DbContext(typeof(EntitiesContext))]
    [Migration("20250403101441_CriacaoTabelas")]
    partial class CriacaoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCurriculum.Models.AcademicExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("course_name");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<int>("Degree")
                        .HasColumnType("int")
                        .HasColumnName("degree");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsStudying")
                        .HasColumnType("bit")
                        .HasColumnName("studying");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StatusFormation")
                        .HasColumnType("int")
                        .HasColumnName("status_formation");

                    b.Property<int>("TypeFormation")
                        .HasColumnType("int")
                        .HasColumnName("types_formations");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("formations");
                });

            modelBuilder.Entity("MyCurriculum.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("zip_code");

                    b.HasKey("AddressId");

                    b.HasIndex("CurriculumId")
                        .IsUnique();

                    b.ToTable("address");
                });

            modelBuilder.Entity("MyCurriculum.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<int?>("TypeCourse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("MyCurriculum.Models.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("genders");

                    b.Property<string>("LinkedIn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("linkedIn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("Picture")
                        .HasMaxLength(100)
                        .HasColumnType("varbinary(100)")
                        .HasColumnName("picture");

                    b.Property<string>("ProfessionalGoals")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("professional_goals");

                    b.HasKey("CurriculumId");

                    b.ToTable("curriculum");
                });

            modelBuilder.Entity("MyCurriculum.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComprehensionLevel")
                        .HasColumnType("int")
                        .HasColumnName("comprehension_level");

                    b.Property<int?>("ConversationLevel")
                        .HasColumnType("int")
                        .HasColumnName("conversation_level");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("language");

                    b.Property<int?>("WritingLevel")
                        .HasColumnType("int")
                        .HasColumnName("writing_level");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("languages");
                });

            modelBuilder.Entity("MyCurriculum.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("URL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("url");

                    b.HasKey("LinkId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("MyCurriculum.Models.ProfessionalExp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActualJob")
                        .HasColumnType("bit")
                        .HasColumnName("actual_job");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("company");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("professional_experiences");
                });

            modelBuilder.Entity("MyCurriculum.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("link");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("project_name");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("MyCurriculum.Models.ProjectTool", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("project_tool");
                });

            modelBuilder.Entity("MyCurriculum.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("ToolName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("tools");
                });

            modelBuilder.Entity("MyCurriculum.Models.AcademicExperience", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("AcademicExperiences")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Address", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithOne("Address")
                        .HasForeignKey("MyCurriculum.Models.Address", "CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Course", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("Courses")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Language", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("Languages")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Link", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("Links")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.ProfessionalExp", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("ProfessionalExperiences")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Project", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("Projects")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.ProjectTool", b =>
                {
                    b.HasOne("MyCurriculum.Models.Project", "Project")
                        .WithMany("ProjectTool")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyCurriculum.Models.Tool", "Tool")
                        .WithMany("ProjectTool")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("MyCurriculum.Models.Tool", b =>
                {
                    b.HasOne("MyCurriculum.Models.Curriculum", null)
                        .WithMany("Tools")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCurriculum.Models.Curriculum", b =>
                {
                    b.Navigation("AcademicExperiences");

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Languages");

                    b.Navigation("Links");

                    b.Navigation("ProfessionalExperiences");

                    b.Navigation("Projects");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("MyCurriculum.Models.Project", b =>
                {
                    b.Navigation("ProjectTool");
                });

            modelBuilder.Entity("MyCurriculum.Models.Tool", b =>
                {
                    b.Navigation("ProjectTool");
                });
#pragma warning restore 612, 618
        }
    }
}
